name: GWP's Website
description: Accomplishments of GWP
twitter_username: GWP
github_username: GWP-TheMasters
author: gwp@gmail.com

markdown: kramdown

theme: minima

header_pages:
  - index.md
  - another_page.md
